spring:
  servlet:
    multipart:
      max-file-size: 10MB  # 파일 한 개당
      max-request-size: 10MB # 요청 당(파일이 여러개라도)

  web:
    resources:
      static-locations: file:///C:uploadFiles/  # 정적 파일의 기본 경로로 설정
